// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
public class Select {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void Select() {
        driver.get("http://texas-parks-database.com/");
        driver.manage().window().setSize(new Dimension(1200, 766));
        driver.findElement(By.id("zipInput")).click();
        driver.findElement(By.id("zipInput")).sendKeys("78705");
        driver.findElement(By.id("model")).click();
        {
            WebElement dropdown = driver.findElement(By.id("model"));
            dropdown.findElement(By.xpath("//option[. = 'Campgrounds']")).click();
        }
        driver.findElement(By.cssSelector(".btn")).click();
        driver.findElement(By.linkText("Cold Springs Campground")).click();
    }
}
